PortKonnect.UserAccessManagemnet.TokenService/Controllers/UserAccountController.cs
using System;
using System.Configuration;
using PortKonnect.Common.Services;
using System.Web;
using System.Web.Mvc;
using PortKonnect.UserAccessManagement.Domain.DTOS;
using PortKonnect.UserAccessManagement.ApplicationServices;
using PortKonnect.UserAccessManagement.Data;
using PortKonnect.UserAccessManagement.Repositories;
using PortKonnect.UserAccessManagement.Repositories.Interfaces;
using PortKonnect.UserAccessManagement.Domain.Repositories;
using PortKonnect.UserAccessManagement.DataServcies;
using IdentityServer3.Core.Extensions;
using PortKonnect.UserAccessManagemnet.TokenService.Common;
using PortKonnect.UserAccessManagement.GlobalConstants;
using System.Collections.Generic;

namespace PortKonnect.UserAccessManagemnet.TokenService.Controllers
{
    public class CustomModel
    {
        public string signin { get; set; } 
        public UserDTO userDTO { get; set; }
    }

    public class UserAccountController : Controller
    {
      
        [HttpGet]
        public ActionResult Index(string signin)
        {

            return View(new UserDTO());
        }


        [HttpPost]
        public ActionResult Index(string signin, UserDTO userDTO)
        {

            IAccountService _accountService = new AccountService();
            IUserContext userContext = new UserContext();
                   ContextDTO contextDto=new ContextDTO();

            IUserRepository userRepository = new UserRepository(userContext);
            IRoleRepository roleRepository = new RoleRepository(userContext);
            ICommonRepository commonRepository = new CommonRepository(userContext);
            INotificationDataService notificationDataService = new NotificationDataService();
            IPartnerRepository partnerRepository = new PartnerRepository(userContext);
            IUserApplicationService _userApplicationService = new UserApplicationService(userContext,userRepository,roleRepository,commonRepository, notificationDataService, partnerRepository);

            _userApplicationService.AddUser(userDTO, contextDto);
           

            return Redirect("~/identity/" + "Login?signin=" + signin);

                
            
        }
        [HttpGet]
        public ActionResult ResetPassword(string signin)
        {
            ViewBag.signin = signin;

            ViewBag.isEmailSuccess = false;
            
            return View(new UserDTO());
        }

      
        [HttpGet]
        public ActionResult BackToLogin()
        {

            return Redirect(ConfigurationManager.AppSettings["uamWebApp"]);
        }

        [HttpGet]
        public ActionResult BackToResetPassword(string signin)
        {

            return RedirectToAction("ResetPassword", new { signin = signin });
        }
        [HttpPost]
        public ActionResult ResetPassword(string signin,UserDTO userDTO)
        {
            string errorMessage = "";
            bool isEmailSuccess = false;

            IUserContext userContext = new UserContext();

            try
            {

                var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
                if (signInMessage.ClientId != null)
                {
                    ClientId client = new ClientId(signInMessage.ClientId);
                    
                    string url = ConfigurationManager.AppSettings["uamapiUrl"];

                    url += "api/Account/TokenServieResetPassword/" + client.ApplicationId+"/"+client.SubscriberId+"/"+userDTO.UserName+"/"+signin+"/"+client.LoggedApplication;

                    string status = ApiClient.RestGet<string>(url);
                   
                    if (status == UAMGlobalConstants.Success)
                    {
                        isEmailSuccess = true;
                    }else
                    {
                        errorMessage = status;
                        isEmailSuccess = false;
                    }
                }
                else
                {
                    errorMessage = "Client Id is  null";
                    isEmailSuccess = false;
                }

            }
            catch(Exception ex)
            {
                isEmailSuccess = false;
                ViewBag.errorMsg = ex.Message;
                errorMessage= ex.Message;
            }

            if (isEmailSuccess)
            {
                ViewBag.isEmailSuccess = true;
            }
            else
            {
                ViewBag.isEmailSuccess = false;
            }
            return RedirectToAction("EmailSent", new { signin = signin, status = isEmailSuccess, errorMessage = errorMessage });
           
        }
        [AllowAnonymous]
        public ActionResult ChangePassword(string LogTransId)
        {           

            UserDTO user = checkUserDetails(LogTransId);
            if (user != null)
            {
                ViewBag.signin = null;
                ViewBag.UserName = user.UserName;
                ViewBag.PassWord = user.Password;
                ViewBag.LogTransId = LogTransId;
                ViewBag.UAMApi = ConfigurationManager.AppSettings["uamapiUrl"];
                ViewBag.RedirectApplicationUrl = ConfigurationManager.AppSettings["MarineUri"];
                return View("ForgotPassword");
            }
            else
            {
                return RedirectToAction("LinkExpired");

            }
        }


        [AllowAnonymous]
        public ActionResult ForgotPassword(string LogTransId,string signin)
        {
            var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
            if (signInMessage?.ClientId != null)
            {
                ClientId client = new ClientId(signInMessage.ClientId);
                //ViewBag.RedirectApplicationUrl = ApiClient.RestGet<string>(ConfigurationManager.AppSettings["uamapiUrl"] + "api/GetApplicationUrl/" + client.ApplicationId + "/" + client.SubscriberId);
                ViewBag.RedirectApplicationUrl = ConfigurationManager.AppSettings["TokenServiceURL"] + "/identity/login?signin=" + signin;
            }
            
            UserDTO user = checkUserDetails(LogTransId);
                if (signInMessage!=null && user != null)
                {
                    ViewBag.UserName = user.UserName;
                    ViewBag.PassWord = user.Password;
                    ViewBag.LogTransId = LogTransId;
                    ViewBag.signin = signin;
                    ViewBag.UAMApi = ConfigurationManager.AppSettings["uamapiUrl"];
                    return View("ForgotPassword");
                }
            else
            {
                signin = null;
                return RedirectToAction("LinkExpired", new { signin });

            }
        }

        [AllowAnonymous]
        public ActionResult PartnerRegistration(string LogTransId, string signin, string loggedApplication)
        {
            List<string> ApplUrls = new List<string>();

            var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
            string url = string.Empty;
            if (signInMessage.ReturnUrl != null)
            {
                 url = HttpUtility.UrlDecode(signInMessage.ReturnUrl);
                 url = url.Substring(url.LastIndexOf("redirect_uri") + 13, url.Length - url.LastIndexOf("redirect_uri") - 13);
            }
            return Redirect(url+"/PartnerRegistration");
        }

        [AllowAnonymous]
        public ActionResult UpdatePartnerRegistration(string LogTransId, string signin, string loggedApplication)
        {
            List<string> ApplUrls = new List<string>();

            var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
            string url = string.Empty;
            if (signInMessage.ReturnUrl != null)
            {
                url = HttpUtility.UrlDecode(signInMessage.ReturnUrl);
                url = url.Substring(url.LastIndexOf("redirect_uri") + 13, url.Length - url.LastIndexOf("redirect_uri") - 13);
            }
            return Redirect(url + "/PartnerRegistrationEdit");
        }

        public UserDTO checkUserDetails(string LogTransId)
        {

            string url = ConfigurationManager.AppSettings["UAMAPIUrl"];
            try
            {
                url += "api/User/ForgetPassword/" + LogTransId;
                UserDTO user = ApiClient.RestGet<UserDTO>(url);
                return user;


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);


            }
        }
        
        [HttpGet]
        public ActionResult SessionExpired(string signin)
        {
            ViewBag.signin = signin;

            var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
            if (signInMessage.ClientId != null)
            {
                ClientId client = new ClientId(signInMessage.ClientId);
                ViewBag.RedirectApplicationUrl = ApiClient.RestGet<string>(ConfigurationManager.AppSettings["uamapiUrl"] + "api/GetApplicationUrl/" + client.ApplicationId + "/" + client.SubscriberId);
            }
         
            return View("SessionExpired");
        }

        [HttpGet]
        public ActionResult LinkExpired(string signin)
        {
            ViewBag.signin = signin;
            if(signin != null)
            {
                var signInMessage = System.Web.HttpContext.Current.Request.GetOwinContext().Environment.GetSignInMessage(signin);
                if (signInMessage != null && signInMessage.ClientId != null)
                {
                    ClientId client = new ClientId(signInMessage.ClientId);

PortKonnect.UserAccessManagemnet.TokenService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")

    <style>
        .page-header {
            padding-bottom: 9px;
            margin: 40px 0 20px;
            border-bottom: 0px solid #eeeeee;
        }

        .navbar-brand {
            float: left;
            padding: 0;
            font-size: 18px;
            line-height: 20px;
        }

        .navbar-brand-login {
            float: left;
            padding: 15px 15px;
            font-size: 18px;
            line-height: 20px;
        }

        .panel-title {
            font-weight: bold;
            text-transform: capitalize;
        }

        .navbar-inverse {
            background-color: #001526;
            border-color: #000;
        }

            .navbar-inverse .navbar-brand {
                color: #fff;
            }


        .navbar {
            min-height: 44px;
        }

        .panel-default > .panel-heading {
            background-color: #001526;
            color: #fff;
        }

        .panel {
            background-color: rgba(25, 57, 89, 0.93);
        }

        body {
            /*background: url(/Content/Styles/images/new4.jpg) no-repeat center center fixed;*/
            background: url(/Content/Images/Background/cargo-bg.jpg) no-repeat center center fixed;
           
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        hr {
            border-top: 0px;
        }


        .input-icon i {
            color: #aaa;
            display: block;
            position: absolute;
            margin: 7px 2px 4px 5px;
            width: 16px;
            height: 16px;
            font-size: 16px;
            text-align: center;
        }

        .input-icon input {
            padding-left: 25px;
        }
    </style>

</head>

<body>

  
    <div id="tt"   class="navbar navbar-inverse navbar-fixed-top">
        <div >
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>*@
                @*<a class="navbar-brand" href="#"><img src="/Content/Images/Background/cargo-bg.jpg" class="header-logo"></a>*@
                @*@Html.ActionLink("Cargo Security Token Service", "BackToLogin", "UserAccount", new { signin = @ViewBag.signin }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>    
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        @*<ng-view></ng-view>*@
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Security Token Service</p>
        </footer>*@
    </div>
    <script src="~/Scripts/Lib/toaster.js"></script>
    <script src="~/Scripts/Application/rootAngular.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>